"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false 
command_timeout = 500
palette = 'my'
#format = "[$directory$git_branch$git_status]($style)$character"
format = """
$kubernetes\
$directory\
( $git_branch)\
( $git_commit)\
$git_state\
$git_status\
$package\
( $golang)\
( $helm)\
( $nodejs)\
( $php)\
( $terraform)\
( $aws)\
( $cmd_duration)\
$jobs\
$battery
$character\
"""

[palettes.my]
git = '#f44d27'
golang = '#007d9c'
helm = '#0f1689'
nodejs = '#417e38'
php = '#4F5B93'
opentofu = '#FFD700'

[character]
error_symbol = "[✗](bold red)"
success_symbol = "[❯](bold green)"

[directory]
truncate_to_repo = false
format = '[$path]($style)[$read_only]($read_only_style)'

[git_branch]
symbol = ''
style = 'bold git'
format = '[$symbol$branch(:$remote_branch)]($style)'

[git_commit]
only_detached = false
style = 'git'
format = '[\($hash$tag\)]($style)'

[git_state]
style = 'bold git'

[git_status]
format     = '[$all_status]($style)'
style      = 'git'
ahead      = "⇡${count}"
diverged   = "⇕⇡${ahead_count}⇣${behind_count}"
behind     = "⇣${count}"

[golang]
style = 'bold golang'
format = '([go]($style) $version)'
version_format = '${major}.${minor}'

[helm]
style = 'bold helm'
format = '([helm]($style) $version)'
version_format = '${major}.${minor}'

[nodejs]
style = 'bold nodejs'
format = '([node]($style) $version)'
version_format = '${major}.${minor}'

[php]
style = 'bold php'
format = '([php]($style) $version)'
version_format = '${major}.${minor}'

[terraform]
style = 'bold opentofu'
format = '([tf]($style) $version)'
version_format = '${major}.${minor}'

[aws]
style = 'yellow'
format = '([aws]($style) ($profile )(\($region\) )(\[$duration\] ))'

[cmd_duration]
min_time = 1_000
show_milliseconds = true
format = '[$duration]($style)'

[[battery.display]]
threshold = 10
style = 'bold red'

[[battery.display]]
threshold = 30
style = 'bold yellow'

